# --- Build stage: needs devDependencies (tailwindcss) to compile the CSS ---
# node:24-alpine on purpose. package-lock.json is generated by npm 11 on Node 24,
# and node:20-alpine ships npm 10.8, which rejected the lockfile and failed the
# Render build at `npm ci`. Matching the version that produced the lock keeps the
# container build identical to what is tested locally.
FROM node:24-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build:css

# --- Runtime stage: production dependencies only, plus the compiled output ---
FROM node:24-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci --omit=dev

COPY server.js ./server.js
# backend/ is the LIVE application code (server.js requires ./backend/src/app and
# ./backend/src/database/connection). Omitting it made the image crash on boot with
# MODULE_NOT_FOUND. The root-level models/routes/middleware are legacy and unused,
# but services/fallbackStore.js is still required by backend/src, so services stays.
COPY backend ./backend
COPY services ./services
COPY --from=build /usr/src/app/public ./public

# Cloud Run sets PORT itself (8080 by default); server.js now honours it.
ENV PORT=8080
EXPOSE 8080

ENV NODE_ENV=production

CMD ["node", "server.js"]
