/**
 * Roles & Permissions Definition
 */

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
  LANDLORD: 'LANDLORD',
  SEEKER: 'SEEKER',
  USER: 'USER'
};

const PERMISSIONS = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  EXPORT: 'EXPORT',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_SYSTEM: 'MANAGE_SYSTEM',
  MODERATE: 'MODERATE',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  SEND_NOTIFICATIONS: 'SEND_NOTIFICATIONS'
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE,
    PERMISSIONS.READ,
    PERMISSIONS.UPDATE,
    PERMISSIONS.DELETE,
    PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT,
    PERMISSIONS.EXPORT,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MODERATE,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.SEND_NOTIFICATIONS
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.CREATE,
    PERMISSIONS.READ,
    PERMISSIONS.UPDATE,
    PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT,
    PERMISSIONS.EXPORT,
    PERMISSIONS.MODERATE,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.READ,
    PERMISSIONS.UPDATE,
    PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT,
    PERMISSIONS.MODERATE
  ],
  [ROLES.LANDLORD]: [
    PERMISSIONS.CREATE,
    PERMISSIONS.READ,
    PERMISSIONS.UPDATE,
    PERMISSIONS.DELETE
  ],
  [ROLES.SEEKER]: [
    PERMISSIONS.CREATE,
    PERMISSIONS.READ,
    PERMISSIONS.UPDATE,
    PERMISSIONS.DELETE
  ],
  [ROLES.USER]: [
    PERMISSIONS.READ
  ]
};

function hasPermission(role, requiredPermission) {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(requiredPermission);
}

function hasAnyRole(userRole, allowedRoles = []) {
  if (!userRole) return false;
  return allowedRoles.includes(userRole);
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  hasAnyRole
};
